### ISSUE TITLE
Error while creating backup of EUW/de

### ISSUE THREAD

**Issue by A-wels** [Nemin32/Charon#1]
I am using your Windows build.
Full Stacktrace in txt file
[stacktrace.txt](https://github.com/Nemin32/Charon/files/4274472/stacktrace.txt)

I am now running the backup on linux. Seems good so far.

**Comment by A-wels** [comment]
Also crashes for EUNE/en on windows, same message

**Comment by Nemin32** [comment]
Hello,

Thank you very much for the issue. I just pushed a patch, which will hopefully fix this.

It will be available under [Alpha2](https://github.com/Nemin32/Charon/releases/tag/alpha2) in a few minutes.
