### ISSUE TITLE
Error at 'Result::unwrap()'

### ISSUE THREAD

**Issue by maltejur** [Nemin32/Charon#6]
While running a while on a EUW backup, I got this:
```
[6719/47822 (14%) (21596)] Heusini [1 new threads]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src\libcore\result.rs:1188:5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src\libcore\result.rs:1188:5
[6720/47822 (14%) (21597)] Uranbrennstab
```
After that, the program just closed.
It looks similar to #1, but the error is a little bit different.

**Comment by Nemin32** [comment]
Hmm, that's certainly annoying. I'll see what I can do, it's probably in the JSON decoding part of the program.

**Comment by Nemin32** [comment]
Please try [this](https://github.com/Nemin32/Charon/releases/tag/alpha5) it *should* fix the problem, but if not please tell me.

**Comment by maltejur** [comment]
I'm trying it now and let it run overnight.

**Comment by maltejur** [comment]
Yea it now works without problems
